import = [
    "~/.config/alacritty/themes/catppuccin-frappe.toml"
]

live_config_reload = true

[env]
TERM = "xterm-256color"


[window]


[font]
normal = {family = "FiraCode Nerd Font", style = "Retina"}
